default_context:
  project_name: 'pb_runner'
  project_slug: 'pb_runner'
  domain_main: 'pb_runner.com'
  domain_staging: 'stag.pb_runner.com'
  docker_swarm_stack_name_main: 'pb_runner-com'
  docker_swarm_stack_name_staging: 'stag-pb_runner-com'
  secret_key: 'mysecret'
  first_superuser: 'admin@pb_runner.com'
  first_superuser_password: 'chefcooking'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.pb_runner.com", "https://stag.pb_runner.com", "https://pb_runner.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@pb_runner.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@pb_runner.com'
  pgadmin_default_user_password: 'chefcooking'
  traefik_constraint_tag: 'pb_runner.com'
  traefik_constraint_tag_staging: 'stag.pb_runner.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:chefcooking'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
